"""Maintained integration awareness catalog.

Capabilities are attached only where this package ships a real adapter.  An
awareness-only entry is useful for diagnostics and install planning, but is
never treated as callable support.
"""

from __future__ import annotations

from typing import Iterable, Optional

from autocausal.integrations.types import (
    CapabilitySpec,
    IntegrationMaturity,
    IntegrationSpec,
    LicensePolicy,
    RuntimeRequirement,
    SecurityProfile,
)


def _cap(
    capability_id: str,
    description: str,
    *,
    deterministic: bool = True,
    production_ready: bool = False,
    caveats: tuple[str, ...] = (),
) -> CapabilitySpec:
    return CapabilitySpec(
        id=capability_id,
        description=description,
        deterministic=deterministic,
        production_ready=production_ready,
        caveats=caveats,
    )


STATS_TEST = _cap(
    "stats.test",
    "Bounded classical statistical tests with structured results.",
    production_ready=True,
)
PARTIAL_CORR = _cap(
    "stats.partial_correlation",
    "Partial correlation after residualizing explicit controls.",
    production_ready=True,
    caveats=("Partial correlation is associational, not causal identification.",),
)
ROBUST_COV = _cap(
    "stats.robust_covariance",
    "OLS covariance and residual diagnostics with robust covariance options.",
    production_ready=True,
)
ML_PREPROCESS = _cap(
    "ml.preprocessing",
    "Leakage-safe sklearn preprocessing pipeline construction.",
    production_ready=True,
)
ML_CLASSIFIER = _cap(
    "ml.tabular_classifier",
    "Bounded tabular classifier estimator factory.",
    production_ready=True,
)
ML_REGRESSOR = _cap(
    "ml.tabular_regressor",
    "Bounded tabular regressor estimator factory.",
    production_ready=True,
)
ML_CV = _cap(
    "ml.cross_validation",
    "Deterministic bounded cross-validation.",
    production_ready=True,
)
ML_METRICS = _cap(
    "ml.metrics",
    "Classification and regression metrics.",
    production_ready=True,
)
TFIDF = _cap(
    "nlp.embeddings.tfidf",
    "Local TF-IDF sparse embeddings.",
    production_ready=True,
)
ESTIMATOR_FACTORY = _cap(
    "ml.estimator_factory",
    "Optional bounded boosted-tree estimator factory.",
    production_ready=True,
)
TUNING = _cap(
    "ml.tune",
    "Trial/time-bounded Optuna study execution.",
    deterministic=False,
)
RESAMPLING = _cap(
    "ml.resampling_pipeline",
    "Fold-local imbalanced-learn sampler pipeline.",
    production_ready=True,
)
EXPLANATION = _cap(
    "ml.explain",
    "Resource-capped predictive SHAP explanation.",
    caveats=("SHAP values explain predictions; they are not causal effects.",),
)
NLP_ENTITIES = _cap(
    "nlp.entities",
    "Local spaCy entity extraction with bounded text size.",
    production_ready=True,
)
NLP_EMBEDDINGS = _cap(
    "nlp.embeddings",
    "Local sentence-transformer embeddings with sample and dimension metadata.",
    deterministic=False,
)
VECTOR_SEARCH = _cap(
    "nlp.vector_search",
    "Bounded local nearest-neighbor search.",
    production_ready=True,
)
CAUSAL_PC = _cap(
    "causal.discovery.pc",
    "PC discovery routed through the existing causal-learn backend.",
    caveats=("Graph discovery assumptions must be reviewed; availability is not validity.",),
)
CAUSAL_DISCOVERY = _cap(
    "causal.discovery",
    "Existing optional causal discovery backend.",
    caveats=("Learned edges are exploratory hypotheses.",),
)
CAUSAL_ATE = _cap(
    "causal.estimate.ate",
    "ATE/CATE estimation routed through an existing engine.",
    caveats=("An estimator does not establish exchangeability or identification.",),
)
CAUSAL_REFUTE = _cap(
    "causal.refute",
    "DoWhy refutation routed through the existing backend.",
    caveats=("Passing refuters does not prove identification.",),
)
VIZ_CHART = _cap(
    "viz.chart",
    "Render an AutoChart ChartSpec through a local backend.",
    production_ready=True,
)
VIZ_DAG = _cap(
    "viz.dag",
    "Render or structure a DAG/network locally.",
    production_ready=True,
    caveats=("A rendered edge is not evidence of a causal effect.",),
)
VIZ_EXPORT = _cap(
    "viz.export",
    "Static Plotly image export through Kaleido.",
    production_ready=True,
)
DATA_VALIDATE = _cap(
    "data.validate",
    "Validate a frame against a caller-supplied Pandera schema.",
    production_ready=True,
)
DATA_CONVERT = _cap(
    "data.convert",
    "Convert tabular data through Polars or Arrow without network access.",
    production_ready=True,
)
MLFLOW_LOG = _cap(
    "ops.mlflow.log_manifest",
    "Log redacted metrics/parameters to an explicitly configured MLflow run.",
)


def _spec(
    integration_id: str,
    category: str,
    package: str,
    import_name: str,
    description: str,
    *,
    license: str,
    license_policy: LicensePolicy,
    maturity: IntegrationMaturity = IntegrationMaturity.AWARENESS,
    capabilities: tuple[CapabilitySpec, ...] = (),
    extra: Optional[str] = None,
    homepage: str = "",
    runtime: tuple[RuntimeRequirement, ...] = (RuntimeRequirement.CPU,),
    compatibility: tuple[str, ...] = (),
    fallback: Optional[str] = None,
    security: SecurityProfile = SecurityProfile(),
    profiles: tuple[str, ...] = (),
    blocked_reason: Optional[str] = None,
) -> IntegrationSpec:
    install_hint = (
        f"pip install 'auto-causal-lib[{extra}]'"
        if extra
        else f"pip install {package}"
    )
    if maturity == IntegrationMaturity.BLOCKED:
        install_hint = "Do not install through AutoCausal: " + (
            blocked_reason or "blocked by maintained catalog policy"
        )
    return IntegrationSpec(
        id=integration_id,
        category=category,
        package=package,
        import_name=import_name,
        description=description,
        install_extra=extra,
        install_hint=install_hint,
        homepage=homepage or f"https://pypi.org/project/{package}/",
        license=license,
        license_policy=license_policy,
        maturity=maturity,
        capabilities=capabilities,
        required_runtime=runtime,
        compatibility=compatibility,
        deterministic_fallback=fallback,
        security=security,
        profiles=profiles,
        blocked_reason=blocked_reason,
    )


P = LicensePolicy.PERMISSIVE
C = LicensePolicy.COPYLEFT
U = LicensePolicy.UNKNOWN
NATIVE = IntegrationMaturity.NATIVE
EXTERNAL = IntegrationMaturity.EXTERNAL
AWARENESS = IntegrationMaturity.AWARENESS
BLOCKED = IntegrationMaturity.BLOCKED


CATALOG: tuple[IntegrationSpec, ...] = (
    _spec(
        "autocausal-native",
        "native",
        "auto-causal-lib",
        "autocausal",
        "Deterministic in-process fallbacks and existing AutoCausal engines.",
        license="MIT",
        license_policy=P,
        maturity=NATIVE,
        capabilities=(
            PARTIAL_CORR,
            ML_CLASSIFIER,
            ML_REGRESSOR,
            TFIDF,
            NLP_EMBEDDINGS,
            VECTOR_SEARCH,
            CAUSAL_PC,
            CAUSAL_ATE,
            VIZ_DAG,
            VIZ_CHART,
        ),
        fallback=None,
        profiles=("stats", "automl", "nlp-full", "causal-extra", "viz", "production", "all-safe"),
    ),
    # Statistics / econometrics
    _spec(
        "numpy",
        "statistics",
        "numpy",
        "numpy",
        "Array and linear-algebra foundation used by native fallbacks.",
        license="BSD-3-Clause",
        license_policy=P,
        profiles=("stats", "production", "all-safe"),
    ),
    _spec(
        "scipy",
        "statistics",
        "scipy",
        "scipy",
        "Statistical tests and distribution functions.",
        license="BSD-3-Clause",
        license_policy=P,
        maturity=EXTERNAL,
        capabilities=(STATS_TEST, PARTIAL_CORR),
        extra="stats",
        fallback="autocausal-native",
        profiles=("stats", "research", "production", "all-safe"),
    ),
    _spec(
        "statsmodels",
        "statistics",
        "statsmodels",
        "statsmodels",
        "Regression, robust covariance, time-series and diagnostics.",
        license="BSD-3-Clause",
        license_policy=P,
        maturity=EXTERNAL,
        capabilities=(ROBUST_COV, PARTIAL_CORR),
        extra="stats",
        fallback="scipy/autocausal-native",
        profiles=("stats", "research", "production", "all-safe"),
    ),
    _spec(
        "pingouin",
        "statistics",
        "pingouin",
        "pingouin",
        "Convenience statistical API; deferred because its GPL license is policy-gated.",
        license="GPL-3.0",
        license_policy=C,
        extra="research",
        profiles=("research",),
    ),
    _spec(
        "linearmodels",
        "econometrics",
        "linearmodels",
        "linearmodels",
        "Panel and instrumental-variable estimators; cataloged for design-aware use.",
        license="NCSA",
        license_policy=P,
        extra="stats",
        profiles=("stats", "causal-extra", "research", "all-safe"),
    ),
    _spec(
        "arch",
        "econometrics",
        "arch",
        "arch",
        "Volatility and time-series econometrics.",
        license="NCSA",
        license_policy=P,
        extra="stats",
        profiles=("stats", "research"),
    ),
    _spec(
        "pymc",
        "statistics",
        "pymc",
        "pymc",
        "Bayesian modeling awareness; resource-heavy sampling is not auto-routed.",
        license="Apache-2.0",
        license_policy=P,
        extra="research",
        compatibility=("CPU-safe but potentially memory/time intensive",),
        profiles=("research",),
    ),
    _spec(
        "arviz",
        "statistics",
        "arviz",
        "arviz",
        "Bayesian diagnostics and visualization awareness.",
        license="Apache-2.0",
        license_policy=P,
        extra="research",
        profiles=("research",),
    ),
    _spec(
        "lifelines",
        "statistics",
        "lifelines",
        "lifelines",
        "Survival analysis awareness; no generic causal survival adapter is claimed.",
        license="MIT",
        license_policy=P,
        extra="stats",
        profiles=("stats", "research", "all-safe"),
    ),
    _spec(
        "scikit-posthocs",
        "statistics",
        "scikit-posthocs",
        "scikit_posthocs",
        "Post-hoc multiple-comparison tests awareness.",
        license="MIT",
        license_policy=P,
        extra="stats",
        profiles=("stats", "research"),
    ),
    _spec(
        "patsy",
        "statistics",
        "patsy",
        "patsy",
        "Formula and design-matrix construction awareness.",
        license="BSD-2-Clause",
        license_policy=P,
        extra="stats",
        profiles=("stats", "production", "all-safe"),
    ),
    # Tabular ML / AutoML / explainability
    _spec(
        "scikit-learn",
        "machine-learning",
        "scikit-learn",
        "sklearn",
        "Preprocessing, bounded estimators, CV, metrics, and TF-IDF.",
        license="BSD-3-Clause",
        license_policy=P,
        maturity=EXTERNAL,
        capabilities=(
            ML_PREPROCESS,
            ML_CLASSIFIER,
            ML_REGRESSOR,
            ML_CV,
            ML_METRICS,
            TFIDF,
            NLP_EMBEDDINGS,
        ),
        extra="automl",
        fallback="autocausal-native",
        profiles=("automl", "nlp-full", "causal-extra", "production", "all-safe"),
    ),
    _spec(
        "xgboost",
        "machine-learning",
        "xgboost",
        "xgboost",
        "Optional CPU-bounded boosted-tree estimator candidate.",
        license="Apache-2.0",
        license_policy=P,
        maturity=EXTERNAL,
        capabilities=(ESTIMATOR_FACTORY, ML_CLASSIFIER, ML_REGRESSOR),
        extra="automl",
        runtime=(RuntimeRequirement.CPU, RuntimeRequirement.NATIVE),
        fallback="scikit-learn",
        profiles=("automl", "research"),
    ),
    _spec(
        "lightgbm",
        "machine-learning",
        "lightgbm",
        "lightgbm",
        "Optional CPU-bounded LightGBM estimator candidate.",
        license="MIT",
        license_policy=P,
        maturity=EXTERNAL,
        capabilities=(ESTIMATOR_FACTORY, ML_CLASSIFIER, ML_REGRESSOR),
        extra="automl",
        runtime=(RuntimeRequirement.CPU, RuntimeRequirement.NATIVE),
        compatibility=("Platform wheel/compiler availability varies",),
        fallback="scikit-learn",
        profiles=("automl", "research"),
    ),
    _spec(
        "catboost",
        "machine-learning",
        "catboost",
        "catboost",
        "Optional CPU-bounded CatBoost estimator candidate.",
        license="Apache-2.0",
        license_policy=P,
        maturity=EXTERNAL,
        capabilities=(ESTIMATOR_FACTORY, ML_CLASSIFIER, ML_REGRESSOR),
        extra="automl",
        runtime=(RuntimeRequirement.CPU, RuntimeRequirement.NATIVE),
        fallback="scikit-learn",
        profiles=("automl", "research"),
    ),
    _spec(
        "optuna",
        "machine-learning",
        "optuna",
        "optuna",
        "Optional trial/time-bounded hyperparameter tuning.",
        license="MIT",
        license_policy=P,
        maturity=EXTERNAL,
        capabilities=(TUNING,),
        extra="automl",
        profiles=("automl", "research", "all-safe"),
    ),
    _spec(
        "imbalanced-learn",
        "machine-learning",
        "imbalanced-learn",
        "imblearn",
        "Resampling pipeline that keeps sampling inside training folds.",
        license="MIT",
        license_policy=P,
        maturity=EXTERNAL,
        capabilities=(RESAMPLING,),
        extra="automl",
        fallback="class_weight in scikit-learn",
        profiles=("automl", "production", "all-safe"),
    ),
    _spec(
        "shap",
        "machine-learning",
        "shap",
        "shap",
        "Resource-capped predictive explanation adapter.",
        license="MIT",
        license_policy=P,
        maturity=EXTERNAL,
        capabilities=(EXPLANATION,),
        extra="automl",
        runtime=(RuntimeRequirement.CPU, RuntimeRequirement.NATIVE),
        profiles=("automl", "research", "all-safe"),
    ),
    _spec(
        "joblib",
        "machine-learning",
        "joblib",
        "joblib",
        "Serialization/parallelism awareness; unsafe untrusted deserialization is never exposed.",
        license="BSD-3-Clause",
        license_policy=P,
        profiles=("automl", "production", "all-safe"),
    ),
    _spec(
        "torch",
        "machine-learning",
        "torch",
        "torch",
        "PyTorch awareness; existing model code remains separately policy-bounded.",
        license="BSD-3-Clause",
        license_policy=P,
        runtime=(RuntimeRequirement.CPU, RuntimeRequirement.NATIVE),
        compatibility=("CUDA is optional and never selected implicitly",),
        profiles=("research",),
    ),
    _spec(
        "tensorflow",
        "machine-learning",
        "tensorflow",
        "tensorflow",
        "TensorFlow awareness only due platform, binary, and accelerator complexity.",
        license="Apache-2.0",
        license_policy=P,
        compatibility=("Awareness-only; no AutoCausal adapter",),
        runtime=(RuntimeRequirement.CPU, RuntimeRequirement.NATIVE),
        profiles=("research",),
    ),
    _spec(
        "mlflow",
        "machine-learning",
        "mlflow",
        "mlflow",
        "Opt-in redacted instrumentation; telemetry and remote tracking stay disabled by default.",
        license="Apache-2.0",
        license_policy=P,
        maturity=EXTERNAL,
        capabilities=(MLFLOW_LOG,),
        extra="production",
        security=SecurityProfile(
            may_access_network=True,
            data_egress=True,
            telemetry_supported=True,
            telemetry_default=False,
        ),
        profiles=("production", "research"),
    ),
    # NLP / embeddings / retrieval
    _spec(
        "nltk",
        "nlp",
        "nltk",
        "nltk",
        "NLTK awareness; AutoCausal's existing NLP subsystem owns token resources.",
        license="Apache-2.0",
        license_policy=P,
        profiles=("nlp-full", "all-safe"),
    ),
    _spec(
        "spacy",
        "nlp",
        "spacy",
        "spacy",
        "Local, bounded entity extraction; models are never auto-downloaded.",
        license="MIT",
        license_policy=P,
        maturity=EXTERNAL,
        capabilities=(NLP_ENTITIES,),
        extra="nlp-full",
        security=SecurityProfile(may_access_network=True),
        fallback="rule/NLTK token features",
        profiles=("nlp-full", "research", "all-safe"),
    ),
    _spec(
        "transformers",
        "nlp",
        "transformers",
        "transformers",
        "Transformer awareness; model loading remains in the separately gated SLM subsystem.",
        license="Apache-2.0",
        license_policy=P,
        security=SecurityProfile(may_access_network=True),
        profiles=("nlp-full", "research"),
    ),
    _spec(
        "sentence-transformers",
        "nlp",
        "sentence-transformers",
        "sentence_transformers",
        "Local-only sentence embeddings unless network access is explicitly approved.",
        license="Apache-2.0",
        license_policy=P,
        maturity=EXTERNAL,
        capabilities=(NLP_EMBEDDINGS,),
        extra="nlp-full",
        runtime=(RuntimeRequirement.CPU, RuntimeRequirement.NATIVE),
        security=SecurityProfile(may_access_network=True),
        fallback="scikit-learn TF-IDF",
        profiles=("nlp-full", "research"),
    ),
    _spec(
        "gensim",
        "nlp",
        "gensim",
        "gensim",
        "Topic/vector model awareness; LGPL makes it policy-gated.",
        license="LGPL-2.1-or-later",
        license_policy=C,
        profiles=("research",),
    ),
    _spec(
        "stanza",
        "nlp",
        "stanza",
        "stanza",
        "Stanford NLP awareness; model downloads are not automatic.",
        license="Apache-2.0",
        license_policy=P,
        security=SecurityProfile(may_access_network=True),
        profiles=("nlp-full", "research"),
    ),
    _spec(
        "textblob",
        "nlp",
        "textblob",
        "textblob",
        "Convenience NLP awareness; no production adapter claimed.",
        license="MIT",
        license_policy=P,
        profiles=("nlp-full", "research"),
    ),
    _spec(
        "keybert",
        "nlp",
        "keybert",
        "keybert",
        "Embedding-based keyword extraction awareness.",
        license="MIT",
        license_policy=P,
        security=SecurityProfile(may_access_network=True),
        profiles=("nlp-full", "research"),
    ),
    _spec(
        "faiss",
        "retrieval",
        "faiss-cpu",
        "faiss",
        "Local FAISS vector search with bounded in-memory indexes.",
        license="MIT",
        license_policy=P,
        maturity=EXTERNAL,
        capabilities=(VECTOR_SEARCH,),
        extra="nlp-full",
        runtime=(RuntimeRequirement.CPU, RuntimeRequirement.NATIVE),
        compatibility=("faiss-cpu wheels are not available on every Python/platform pair",),
        fallback="autocausal-native cosine search",
        profiles=("nlp-full", "research"),
    ),
    _spec(
        "chromadb",
        "retrieval",
        "chromadb",
        "chromadb",
        "Local ephemeral Chroma vector search; remote clients are not accepted by the adapter.",
        license="Apache-2.0",
        license_policy=P,
        maturity=EXTERNAL,
        capabilities=(VECTOR_SEARCH,),
        extra="nlp-full",
        security=SecurityProfile(may_access_network=True, data_egress=True),
        fallback="autocausal-native cosine search",
        profiles=("nlp-full", "research"),
    ),
    # Causal discovery / inference
    _spec(
        "causal-learn",
        "causal",
        "causal-learn",
        "causallearn",
        "PC/GES/FCI discovery through the existing soft backend.",
        license="MIT",
        license_policy=P,
        maturity=EXTERNAL,
        capabilities=(CAUSAL_PC, CAUSAL_DISCOVERY),
        extra="causal-extra",
        fallback="autocausal-native pc_lite",
        profiles=("causal-extra", "research"),
    ),
    _spec(
        "dowhy",
        "causal",
        "dowhy",
        "dowhy",
        "DoWhy refutation through the existing backend.",
        license="MIT",
        license_policy=P,
        maturity=EXTERNAL,
        capabilities=(CAUSAL_REFUTE,),
        extra="causal-extra",
        fallback="native placebo refuter",
        profiles=("causal-extra", "research"),
    ),
    _spec(
        "econml",
        "causal",
        "econml",
        "econml",
        "LinearDML/CausalForest estimation through the existing backend.",
        license="MIT",
        license_policy=P,
        maturity=EXTERNAL,
        capabilities=(CAUSAL_ATE,),
        extra="causal-extra",
        runtime=(RuntimeRequirement.CPU, RuntimeRequirement.NATIVE),
        fallback="autocausal-native AIPW/OLS association path",
        profiles=("causal-extra", "research"),
    ),
    _spec(
        "doubleml",
        "causal",
        "DoubleML",
        "doubleml",
        "DoubleML partially linear estimation through the existing backend.",
        license="BSD-3-Clause",
        license_policy=P,
        maturity=EXTERNAL,
        capabilities=(CAUSAL_ATE,),
        extra="causal-extra",
        fallback="autocausal-native AIPW/OLS association path",
        profiles=("causal-extra", "research"),
    ),
    _spec(
        "lingam",
        "causal",
        "lingam",
        "lingam",
        "DirectLiNGAM through the existing discovery backend.",
        license="MIT",
        license_policy=P,
        maturity=EXTERNAL,
        capabilities=(CAUSAL_DISCOVERY,),
        extra="causal-extra",
        fallback="autocausal-native pc_lite",
        profiles=("causal-extra", "research"),
    ),
    _spec(
        "gcastle",
        "causal",
        "gcastle",
        "castle",
        "gCastle NOTEARS through the existing discovery backend.",
        license="Apache-2.0",
        license_policy=P,
        maturity=EXTERNAL,
        capabilities=(CAUSAL_DISCOVERY,),
        extra="causal-extra",
        runtime=(RuntimeRequirement.CPU, RuntimeRequirement.NATIVE),
        compatibility=("Optional deep-learning backends may impose additional constraints",),
        fallback="autocausal-native pc_lite",
        profiles=("causal-extra", "research"),
    ),
    _spec(
        "tigramite",
        "causal",
        "tigramite",
        "tigramite",
        "Time-series causal discovery awareness; GPL use requires explicit policy approval.",
        license="GPL-3.0",
        license_policy=C,
        profiles=("research",),
    ),
    _spec(
        "pgmpy",
        "causal",
        "pgmpy",
        "pgmpy",
        "Probabilistic graphical model awareness; no generic causal adapter claimed.",
        license="MIT",
        license_policy=P,
        extra="causal-extra",
        profiles=("causal-extra", "research"),
    ),
    _spec(
        "causalml",
        "causal",
        "causalml",
        "causalml",
        "Uplift modeling awareness; deferred pending environment-specific compatibility review.",
        license="Apache-2.0",
        license_policy=P,
        compatibility=("Large compiled dependency surface; no stale uplift dependency is bundled",),
        profiles=("research",),
    ),
    _spec(
        "pysensemakr",
        "causal",
        "PySensemakr",
        "sensemakr",
        "Sensitivity-analysis awareness; adapter deferred until API compatibility is pinned.",
        license="MIT",
        license_policy=P,
        profiles=("causal-extra", "research"),
    ),
    _spec(
        "py-tetrad",
        "causal",
        "py-tetrad",
        "pytetrad",
        "Tetrad wrapper awareness only; requires a separately managed Java runtime.",
        license="unknown/mixed",
        license_policy=U,
        runtime=(RuntimeRequirement.CPU, RuntimeRequirement.JAVA),
        compatibility=("Java runtime and Tetrad artifacts required",),
        security=SecurityProfile(executes_external_code=True),
        profiles=("research",),
    ),
    _spec(
        "causalnex",
        "causal",
        "causalnex",
        "causalnex",
        "Blocked by stale Python/dependency constraints.",
        license="Apache-2.0",
        license_policy=P,
        maturity=BLOCKED,
        blocked_reason="Unmaintained release line and incompatible modern Python/networkx constraints.",
    ),
    _spec(
        "cdt",
        "causal",
        "cdt",
        "cdt",
        "Blocked/deprioritized due stale dependencies, GPL policy, and external R/GPU methods.",
        license="GPL-3.0",
        license_policy=C,
        maturity=BLOCKED,
        runtime=(RuntimeRequirement.CPU, RuntimeRequirement.R),
        security=SecurityProfile(executes_external_code=True),
        blocked_reason="Stale dependency surface and many methods require separately managed R/CUDA runtimes.",
    ),
    # Data quality / visualization / data paths
    _spec(
        "pandera",
        "data-quality",
        "pandera",
        "pandera",
        "Caller-supplied frame schema validation.",
        license="MIT",
        license_policy=P,
        maturity=EXTERNAL,
        capabilities=(DATA_VALIDATE,),
        extra="production",
        fallback="AutoCausal QC",
        profiles=("production", "all-safe"),
    ),
    _spec(
        "great-expectations",
        "data-quality",
        "great-expectations",
        "great_expectations",
        "Great Expectations awareness; context/checkpoint orchestration is not auto-executed.",
        license="Apache-2.0",
        license_policy=P,
        extra="research",
        security=SecurityProfile(may_access_network=True, data_egress=True),
        profiles=("research",),
    ),
    _spec(
        "ydata-profiling",
        "data-quality",
        "ydata-profiling",
        "ydata_profiling",
        "Profiling awareness; potentially expensive HTML generation is not auto-routed.",
        license="MIT",
        license_policy=P,
        profiles=("research",),
    ),
    _spec(
        "matplotlib",
        "visualization",
        "matplotlib",
        "matplotlib",
        "Headless AutoChart rendering.",
        license="PSF-based",
        license_policy=P,
        maturity=EXTERNAL,
        capabilities=(VIZ_CHART,),
        extra="viz",
        fallback="AutoChart data/spec",
        profiles=("viz", "production", "all-safe"),
    ),
    _spec(
        "seaborn",
        "visualization",
        "seaborn",
        "seaborn",
        "Statistical visualization awareness; AutoChart uses backend-neutral specs.",
        license="BSD-3-Clause",
        license_policy=P,
        extra="viz",
        profiles=("viz", "research", "all-safe"),
    ),
    _spec(
        "plotly",
        "visualization",
        "plotly",
        "plotly",
        "Interactive/headless AutoChart rendering and DAG display.",
        license="MIT",
        license_policy=P,
        maturity=EXTERNAL,
        capabilities=(VIZ_CHART, VIZ_DAG),
        extra="viz",
        fallback="matplotlib/AutoChart data spec",
        profiles=("viz", "production", "all-safe"),
    ),
    _spec(
        "kaleido",
        "visualization",
        "kaleido",
        "kaleido",
        "Static Plotly export through an installed local image engine.",
        license="MIT",
        license_policy=P,
        maturity=EXTERNAL,
        capabilities=(VIZ_EXPORT,),
        extra="viz",
        runtime=(RuntimeRequirement.CPU, RuntimeRequirement.NATIVE),
        fallback="HTML/JSON chart artifact",
        profiles=("viz", "production", "all-safe"),
    ),
    _spec(
        "networkx",
        "visualization",
        "networkx",
        "networkx",
        "Local graph construction/layout for DAG specifications.",
        license="BSD-3-Clause",
        license_policy=P,
        maturity=EXTERNAL,
        capabilities=(VIZ_DAG,),
        extra="viz",
        fallback="AutoChart graph spec",
        profiles=("viz", "production", "all-safe"),
    ),
    _spec(
        "graphviz",
        "visualization",
        "graphviz",
        "graphviz",
        "Graphviz Python bindings awareness; native Graphviz executable is separate.",
        license="MIT (Python package); native runtime separately licensed",
        license_policy=P,
        extra="viz",
        runtime=(RuntimeRequirement.CPU, RuntimeRequirement.NATIVE),
        compatibility=("Requires Graphviz executable on PATH for rendering",),
        security=SecurityProfile(executes_external_code=True),
        profiles=("viz", "research"),
    ),
    _spec(
        "polars",
        "data",
        "polars",
        "polars",
        "Local pandas/Arrow/Polars conversion adapter.",
        license="MIT",
        license_policy=P,
        maturity=EXTERNAL,
        capabilities=(DATA_CONVERT,),
        extra="production",
        runtime=(RuntimeRequirement.CPU, RuntimeRequirement.NATIVE),
        fallback="pandas",
        profiles=("production", "all-safe"),
    ),
    _spec(
        "pyarrow",
        "data",
        "pyarrow",
        "pyarrow",
        "Local Arrow table conversion and data-path adapter.",
        license="Apache-2.0",
        license_policy=P,
        maturity=EXTERNAL,
        capabilities=(DATA_CONVERT,),
        extra="production",
        runtime=(RuntimeRequirement.CPU, RuntimeRequirement.NATIVE),
        fallback="pandas",
        profiles=("production", "all-safe"),
    ),
)


def catalog_specs() -> tuple[IntegrationSpec, ...]:
    return CATALOG


def catalog_by_id() -> dict[str, IntegrationSpec]:
    return {item.id: item for item in CATALOG}


def iter_catalog(*, category: Optional[str] = None) -> Iterable[IntegrationSpec]:
    for item in CATALOG:
        if category is None or item.category == category:
            yield item


__all__ = ["CATALOG", "catalog_by_id", "catalog_specs", "iter_catalog"]
